---
- name: Install Docker
  hosts: remote_servers
  become: true

  roles:
    - docker


- name: Build and push Docker image
  hosts: "{{ 'remote_servers' if build_on_remote | default(false) | bool else 'localhost' }}"
  connection: "{{ 'ssh' if build_on_remote | default(false) | bool else 'local' }}"
  gather_facts: "{{ build_on_remote | default(false) | bool }}"
  become: "{{ build_on_remote | default(false) | bool }}"

  roles:
    - build-and-push


- name: Deploy application to remote servers
  hosts: remote_servers
  become: true

  roles:
    - deploy-with-compose