---
- name: Install Docker
  hosts: remote_servers
  become: true
  tags:
    - docker
    - install

  roles:
    - docker


- name: Build and push Docker image
  hosts: remote_servers
  become: true
  tags:
    - build
    - push

  roles:
    - build-and-push


- name: Deploy application to remote servers
  hosts: remote_servers
  become: true
  tags:
    - deploy
    - compose

  roles:
    - deploy-with-compose